### ISSUE TITLE
Universal Recommender on Heroku

### ISSUE THREAD

**Issue by DanielShox** [heroku/predictionio-buildpack#15]
Got the Universal Rec. working locally but can't get it to build after deploying the engine to Heroku i.e. run the release command.

`Exception in thread "main" java.lang.IllegalStateException: No Elasticsearch client configuration detected, check your pio-env.sh forproper configuration setting`

My pio-env.sh file for the eventserver contains:

```
PIO_STORAGE_REPOSITORIES_METADATA_NAME=pio_meta
PIO_STORAGE_REPOSITORIES_METADATA_SOURCE=ELASTICSEARCH # testing this
PIO_STORAGE_REPOSITORIES_EVENTDATA_NAME=pio_event
PIO_STORAGE_REPOSITORIES_EVENTDATA_SOURCE=HBASE
PIO_STORAGE_REPOSITORIES_MODELDATA_NAME=pio_model
PIO_STORAGE_REPOSITORIES_MODELDATA_SOURCE=HDFS

PIO_STORAGE_SOURCES_ELASTICSEARCH_TYPE=elasticsearch
PIO_STORAGE_SOURCES_ELASTICSEARCH_CLUSTERNAME=xxxxx
PIO_STORAGE_SOURCES_ELASTICSEARCH_HOSTS=us-east-1.bonsaisearch.net
PIO_STORAGE_SOURCES_ELASTICSEARCH_PORTS=9200
PIO_STORAGE_SOURCES_ELASTICSEARCH_HOME=https://xxxx:xxxx@xxxxx.us-east-1.bonsaisearch.net
```

This is obviously wrong but wondering where I'm making the mistake, I've tried a few variations all yielding the same error...

I also get a :

`[ERROR] [Console$] Unable to locate a proper Apache Spark installation. Aborting.`

When I run pio status.
I'm using the Bonsai ElasticSearch Addon in Heroku so I guess I need to get a Spark instance on Heroku also?

Thanks.

**Comment by mars** [comment]
Hi @DanielShox ,

We do not have an example of the Universal Recommender working on Heroku, so I can only help guide you with the facts that I do have:

1. Make sure you using the [ActionML UniversalRecommender](https://github.com/actionml/universal-recommender). It is the only one updated for the current version of PIO, 0.10.0-incubating. Picking the right engine template can be confusing.
1. Any errors you see during the engine's build & train are probably due to something wrong in the engine, not the eventserver.
1. The eventdata source is shared between the eventserver & the engine. The same source will need to be configured for both.
1. Unless you have a separate external Hbase deployment, I believe your best option to get this running is to switch to PostgreSQL for as the eventdata source. See the PostgrSQL `heroku addons:create` & `heroku addons:attach` process in the [buildpack docs](https://github.com/heroku/predictionio-buildpack/blob/master/CUSTOM.md).
1. Only the Universal Recommender engine requires Elasticsearch. It will do nothing attached to the eventserver.
1. Spark is included in the buildpack. If you're setting up your own `pio-env.sh`, make sure you copy over the `SPARK_*` variables from the [default env file](https://github.com/heroku/predictionio-buildpack/blob/master/config/pio-env.sh#L12). Without those variables, things on Heroku will not work correctly.

I wish I had clearer answers for you. There's a [Universal Recommender users group](https://groups.google.com/forum/#!forum/actionml-user) where you can get answers to questions that are not Heroku-specific.

Also, the Elasticsearch credentials pasted above are now visible to the world. I've edited to remove them. Careful with the secrets!

**Comment by DanielShox** [comment]
Hi Mars,

Thanks for the advice, much appreciated. Will let you know if I manage to get this up on Heroku.

Cheers.

**Comment by mars** [comment]
We're looking into running the Universal Recommender. I don't have a timeline for you, things are busy right now, but I will update this issue when we have results to share.

**Comment by DanielShox** [comment]
@mars  Just a little confused by one of your points above:

> Make sure you're using the ActionML UniversalRecommender. It is the only one updated for the current version of PIO, 0.10.0-incubating. Picking the right engine template can be confusing.

But the docs say that any version > v0.3.0 requires PredictionIO-0.9.7-aml ?

I forked this repo and added a download of elasticsearch into the vendors folder (Not sure if this is even needed with the addon?) ...I can deploy & build on Heroku but the train fails with an R15 error : (

**Comment by DanielShox** [comment]
along with:

`2016-12-14T08:22:46.651799+00:00 app[web.1]: [ERROR] [Console$] No valid engine instance found for engine uiJbR5SLgUpIbRXC0Bj5ZS1x6XimiD3M 1027c857d129d2e4093bed171ecb5edd56d86b8b.
2016-12-14T08:22:46.651812+00:00 app[web.1]: Try running 'train' before 'deploy'. Aborting.`

**Comment by mars** [comment]
Hi Daniel, I just saw this post. Since this is open I'll follow up:

I'm not sure what's gone wrong here. "No valid engine instance found" means that either training did not complete or the trained model was not persisted in a place that the `web` process can access it. That error was logged by the `web` process, not `release`. Was there an error during `release`?

**Comment by dannyshox** [comment]
Hi Mars,

It builds but fails on train (release). I subsequently started getting this error :

`       [INFO] [Console$] Build finished successfully.
       [INFO] [Console$] Looking for an engine...
       [INFO] [Console$] Found template-scala-parallel-universal-recommendation_2.10-0.2.3.jar
       [INFO] [Console$] Found template-scala-parallel-universal-recommendation-assembly-0.2.3-deps.jar
       [INFO] [plugins] [Annex] loaded [], sites []
       [INFO] [RegisterEngine$] Registering engine b9e0hiv8dxaf5QXERpqenxjUm7Le6diB 1027c857d129d2e4093bed171ecb5edd56d86b8b
Exception in thread "main" org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []`

**Comment by mars** [comment]
Good morning @dannyshox,

We just spent several days working to deploy Universal Recommender [UR] on Heroku and found a critical incompatibility. UR requires Elasticsearch [ES], which at first seemed like a surmountable issue because ES is available as a Heroku Add-on. In fact three different ES add-ons are available; we chose to start with Bonsai https://elements.heroku.com/addons/bonsai

After extensive work to configure and deploy the UR engine with Elasticsearch via Bonsai, it was still not connecting to ES. I reached out on the PredictionIO Slack to ask about configuring Universal Recommender for a cloud-based Elasticsearch. Pat of ActionML replied, and here are the facts that came to light:

**Universal Recommender is not currently compatible with cloud-based Elasticsearch.** UR is designed to run on a private, secure network alongside Elasticsearch 1.x. UR requires two interfaces to ES:

  1. REST/HTTP API (used by the UR engine/algorithm)
  2. native/binary transport (used by the UR engine/algorithm and PredictionIO for metadata storage)

Only the REST API is available from the cloud providers, so UR cannot fully connect to cloud-based Elasticsearch. While techniques like network peering or tunneling to an ES cluster might solve this, they would not provide an approachable Heroku developer experience.

We've discussed this issue with PredictionIO folks, and they are prioritizing upgrading PredictionIO metadata storage and UR to support Elasticsearch 2.x as well as migrating to pure REST-interface. These revisions would be targeted to enable UR deployment on Heroku and other containerized cloud platforms. The timeline is likely months before a stable PIO release with these revisions in place.

For my team, this means we are switching our reference app development efforts over to a less-sophisticated ALS-based recommendation engine. Eventually when UR becomes compatible, we will switch back to it.

**Comment by dannyshox** [comment]
Hi Mars,

Thanks for the detailed update. That's unfortunate for now but seems promising for the future. Our team has chosen pretty much the same route, we're happy enough to start with a basic recommender and gradually try and improve on the model's results/errors.

Good luck!

**Comment by mars** [comment]
Update: experimental support for the Universal Recommender is [now available](https://github.com/heroku/predictionio-buildpack/releases/tag/v7.1.0).

**Comment by mars** [comment]
Final update 🏁 the [Universal Recommender on Heroku](https://github.com/heroku/predictionio-engine-ur) is now available.

**Comment by dannyshox** [comment]
Thanks Mars!
