### ISSUE TITLE
You do not have access to the app error

### ISSUE THREAD

**Issue by kamipatel** [heroku/predictionio-buildpack#19]
Hi, I am getting this issue "You do not have access to the app kamapp"
heroku config:set PIO_EVENTSERVER_HOSTNAME=piotwoserver.herokuapp.com PIO_EVENTSERVER_ACCESS_KEY={secret redacted} PIO_EVENTSERVER_APP_NAME=kamapp PIO_EVENTSERVER_PORT=80 --app kamapp
Just not working.... Please help.

**Comment by mars** [comment]
Sounds like one of these steps has not been completed:

* [Create a PredictionIO app in the eventserver](https://github.com/heroku/predictionio-buildpack/blob/master/CUSTOM.md#create-a-predictionio-app-in-the-eventserver)
* [Configure the Heroku app to use the eventserver](https://github.com/heroku/predictionio-buildpack/blob/master/CUSTOM.md#configure-the-heroku-app-to-use-the-eventserver)

**Comment by kamipatel** [comment]
Thanks for prompt reply.
I retried creating new engine... I did miss a step to attach postgres which is even before the heroku config step. Getting same error for "heroku addons:attach". Following is log... Thanks!
 heroku create myengine
Creating ⬢ myengine... done
https://myengine.herokuapp.com/ | https://git.heroku.com/myengine.git
kamleshpate-ltm:predictionio-engine-classification kamlesh.patel$ heroku run "pio app new myapp" -a piotwoserver
Running pio app new myapp on ⬢ piotwoserver... up, run.9762 (Free)
Autoset Spark memory params for web process: --executor-memory 256m --driver-memory 256m 
Autoset Spark memory params for training: --executor-memory 256m --driver-memory 256m 
/app/pio-engine/PredictionIO-dist/vendors/spark-hadoop is probably an Apache Spark development tree. Please make sure you are using at least 1.3.0.
[INFO] [App$] Initialized Event Store for this app ID: 5.
[INFO] [App$] Created new app:
[INFO] [App$]       Name: myapp
[INFO] [App$]         ID: 5
[INFO] [App$] Access Key: OqORFcFf9qvoVxcO58RsnVom1wi4TOk1SLd5zODiy2RmBGobCn2yJbMXbiUDl6eP

heroku addons:attach postgresql-fluffy-85369 --app myapp
Attaching postgresql-fluffy-85369 to ⬢ myapp... !
 ▸    You do not have access to the app myapp.

**Comment by mars** [comment]
There are two "app names" for an engine which are easily confused:

1. apps in the PredictionIO Eventserver
  * data/event storage scopes (essentially tables in the database)
  * created with `heroku run "pio app new …"`
  * use the access key to post & query events in the Eventserver
2. Heroku app names
  * instances of web services running on Heroku
  * created with `heroku create …`
  * accessible at **https://app-name.herokuapp.com**

It looks like when you attempt to attach PostgreSQL, that argument should reference the Heroku app name `--app myengine` instead of the PredictionIO Eventserver app name.

**Comment by kamipatel** [comment]
wow you are right! It worked... Thank you so much!
