### ISSUE TITLE
Can't find Spark

### ISSUE THREAD

**Issue by mgcdanny** [heroku/predictionio-buildpack#26]
I believe the buildpack is setting the location of spark to:
/app/pio-engine/PredictionIO-dist/vendors/spark-hadoop

but when I run heroku run bash I find it here:
/app/PredictionIO-dist/vendors/spark-hadoop

**Comment by mgcdanny** [comment]
Never mind.  Even though heroku run pio app status throws a warning it seems to work anyway

**Comment by mars** [comment]
Due to requirements of the PredictionIO-Heroku build process, there are two possible distribution paths depending on what is deployed with the buildpack:

1. `/app/pio-engine/PredictionIO-dist` for an **Engine**
2. `/app/PredictionIO-dist` for an **Eventserver**

The `pio` command is available on the `PATH` in either case.

**Engine**-specific commands must be run from within the `/app/pio-engine` directory.
